server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/VaccinationCenterDb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  application:
    name: VACCINATION-CENTER-SERVICE